//
//  UIColor+FURYAdditions.swift
//
//  Generated by Zeplin on 12/7/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {

	@nonobjc class var furyClassicGradientTop: UIColor { 
		return UIColor(named: "classicGradientTop")!
	}

	@nonobjc class var furyIntervalGradientTop: UIColor { 
		return UIColor(named: "intervalGradientTop")!
	}

	@nonobjc class var furyCountdownGradientTop: UIColor { 
		return UIColor(named: "countdownGradientTop")!
	}

	@nonobjc class var furyPinkRed: UIColor { 
		return UIColor(named: "pinkRed")!
	}

	@nonobjc class var furyGoldenYellow: UIColor { 
		return UIColor(named: "goldenYellow")!
	}

	@nonobjc class var furyBrightLavender: UIColor { 
		return UIColor(named: "brightLavender")!
	}

	@nonobjc class var furyOpacityButton: UIColor { 
		return UIColor(named: "opacityButton")!
	}

	@nonobjc class var furyBackgroundColor: UIColor { 
		return UIColor(named: "backgroundColor")!
	}

	@nonobjc class var furyCountdownGradientBot: UIColor { 
		return UIColor(named: "countdownGradientBot")!
	}

	@nonobjc class var furyClassicGradientBot: UIColor { 
		return UIColor(named: "classicGradientBot")!
	}

	@nonobjc class var furyIntervalGradientBot: UIColor { 
		return UIColor(named: "intervalGradientBot")!
	}
}
