//
//  UIFont+FURYAdditions.swift
//
//  Generated by Zeplin on 12/7/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {

	@nonobjc class var furyCountdownNumbers: UIFont {
		return UIFont(name: "Oswald-Medium", size: 256.0)!
	}

	@nonobjc class var furyTimerHorizontal: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 180.0)!
	}

	@nonobjc class var furyPickerNumbersActive: UIFont {
		return UIFont(name: "Oswald-Medium", size: 156.0)!
	}
    
    @nonobjc class var furySmallPickerNumbersActive: UIFont {
        return UIFont(name: "Oswald-Medium", size: 96.0)!
    }

	@nonobjc class var furyTimerVertical: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 94.0)!
	}

	@nonobjc class var furyTimerResult: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 80.0)!
	}

	@nonobjc class var furyHeadline1: UIFont {
		return UIFont(name: "Montserrat-Bold", size: 38.0)!
	}

	@nonobjc class var furyHeadline2: UIFont {
		return UIFont(name: "Montserrat-Bold", size: 22.0)!
	}

	@nonobjc class var furyButtonText: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 22.0)!
	}

	@nonobjc class var furyButtonTextDark: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 22.0)!
	}

	@nonobjc class var furyButtonTextRed: UIFont {
		return UIFont(name: "RobotoCondensed-Bold", size: 22.0)!
	}

	@nonobjc class var furyRegularTextBold: UIFont {
		return UIFont(name: "Montserrat-Bold", size: 18.0)!
	}

	@nonobjc class var furyRegularText: UIFont {
		return UIFont(name: "Montserrat-SemiBold", size: 18.0)!
	}

	@nonobjc class var furySmallText: UIFont {
		return UIFont(name: "Montserrat-SemiBold", size: 12.0)!
	}
}
